import speech_recognition as sr
from pocketsphinx import LiveSpeech
import re
import time
from commands import *

# Initialize microphone and recognizer
rc = sr.Recognizer()
source = sr.Microphone()


def callback(rc, audio):
    '''
    PARAMS:
        rc:sr.Recognizer object: recognizer object for audio processing
        audio:audio object: Audio generated by user speech.
    RETURNS: None
    DESC: 
        Callback function when audio is heard. This function is 
        called in a separate thread (created by the listen_in_background
        function call).
    '''
    # key-words to initiate command listening
    keywords = [('hey akira', 1), ('akira', 1)] 
    
    try:
        speech_as_text = rc.recognize_sphinx(audio, keyword_entries=keywords)

        # Look for your "hey akira" keyword in speech_as_text
        if "akira" in speech_as_text or "hey akira":
            recognize_main()

    except sr.UnknownValueError:
        print("Speech unrecognizable")



def recognize_main():
    '''
    PARAMS: None
    RETURNS: None
    DESC: 
        Listen for the user to issue a command to Akira. 
        After a command is issued, identify the command
        (handled by process_command), and execute it.
    '''

    # Begin listening for accompanying command
    print("Activated. Recognizing main command...")
    audio_data = rc.listen(source, phrase_time_limit=5)
    command = rc.recognize_google(audio_data).lower()

    # Identify command type
    c_type, terms = process_command(command)

    if c_type == 'web_search':
        web_search(terms)
    else:
        print('unknown')
    

def process_command(command):
    '''
    PARAMS:
        command:str: full spoken command issued to Akira
    RETURNS:
        result:tuple: Contains the following data:
            c_type:string: command type
            clipped:string: full command with identifying keyword stub removed
    DESC: Process command type
    ''' 
    websearch_kwds = set(['look up', 'google', 'search'])

    result = (None, None)
    parsed = command.split(' ')
    parsed = strip_prefix(parsed)

    if parsed[0] in websearch_kwds or parsed[0]+' '+parsed[1] in websearch_kwds:
        c_type = 'web_search'

        if parsed[0] in websearch_kwds:
            parsed.pop(0)
        else:
            parsed = parsed[2:]

        result = (c_type, ' '.join(parsed))

    return result


def strip_prefix(command):
    '''
    PARAMS:
        command:list: parsed command to process
    RETURNS:
        command:list: command stripped of its prefix words
    DESC:
        Strip any needless keyword at the start of the command.
        return the command stripped of its prefix words.
    '''
    remove = set(['can you', 'could you', 'will you', 'please', 'uh', 'um'])
    
    while command and command[0] in remove:
        command = command[1:]


    return command


def mainloop():
    '''
    PARAMS: None
    RETURNS: None
    DESC:
        Program entry point & main function.
        This function spawns a new thread that will listen in the 
        background for the user to initiate command to Akira.
    '''
    # Create background thread for command listening
    rc.listen_in_background(source, callback, phrase_time_limit=3)
    time.sleep(10000) # Time to listen


mainloop()
